apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: clair
  name: clair
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clair
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: clair
    spec:
      containers:
        - args:
            - -config
            - /config/config.yaml
          image: quay.io/coreos/clair:latest
          name: clair
          ports:
            - containerPort: 6060
            - containerPort: 6061
          resources: {}
          volumeMounts:
            - mountPath: /config/config.yaml
              subPath: config.yaml
              name: clair-config
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      restartPolicy: Always
      volumes:
        - name: clair-config
          configMap:
             name: clair-config
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
